services:
  app_blue: &app
    image: pxuanbach/immersedincode-blog
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: 5
    deploy:
      mode: replicated
      replicas: 2
    ports: 
      - target: 80
        published: "8001-8002"
        protocol: tcp
        mode: host

  app_green:
    <<: *app
    ports: 
      - target: 80
        published: "8005-8006"
        protocol: tcp
        mode: host
      